### ISSUE TITLE
Model Size

### ISSUE THREAD

**Issue by eugenevinitsky** [oxwhirl/smac#10]
Dear authors,

In the paper, it is not clear what the FCN model size is in the first set of layers before the GRU. Would it be possible to clarify this? Or release the model here on github?

**Comment by samvelyan** [comment]
Dear @eugenevinitsky.

The architecture of the agent networks can be found [here](https://github.com/oxwhirl/pymarl/blob/master/src/modules/agents/rnn_agent.py). In the paper, we set rnn_hidden_dim = 64.
