### ISSUE TITLE
Problems running run_qmix.py

### ISSUE THREAD

**Issue by bborj** [oxwhirl/smac#107]
Hi! Maybe this question sounds weird, but i am having problems running "run_qmix.py", i directly copied the repository from GitHub, and then i executed the .py like this:
`python run_qmix.py`
And i have problems with the importation of "Model".
`from smac.examples.rllib.env import RLlibStarCraft2Env
ModuleNotFoundError: No module named 'smac'`
I don't know if maybe i should modify all the importations from other notebooks or what is happening.
Thanks for your help!

**Comment by samvelyan** [comment]
Seems like the the `smac` repository is not properly installed in your environment. Try using the following command within the Jupyter notebook:

```
!pip install git+https://github.com/oxwhirl/smac.git
```
