### ISSUE TITLE
Map difficulties

### ISSUE THREAD

**Issue by LXXXXR** [oxwhirl/smac#108]
Hi,

Thank you for the awesome work. 

Where can I find the exhaustive list of map difficulties please(e.g. esay, medium, hard, super hard)? I found the list of SMAC maps [here](https://github.com/oxwhirl/smac/blob/master/docs/smac.md#environment-settings) as well as in your paper, but difficulties are not provided. and I noticed some inconsistencies among super difficult maps shown in different papers later. So it would be really helpful if you could kindly provide a pointer on where I can find such information. 

Thanks.

**Comment by samvelyan** [comment]
The difficulties are provided in the SMAC paper’s Results section. Hope this helps.
