### ISSUE TITLE
Add new units into a map

### ISSUE THREAD

**Issue by YeeCY** [oxwhirl/smac#13]
I want to add some new RL units into a map with the editor. The second to last paragraph of the documentation mentions the difference between "RL" and regular units. I tried to modify the corresponding options in the editor, but it doesn't work when smac trying to 'Sending ResponseJoinGame'. It seemed stuck forever... Any suggestion?

**Comment by samvelyan** [comment]
I have just prepared a step-by-step tutorial that you can use. Please take a look [here](https://docs.google.com/document/d/1BfAM_AtZWBRhUiOBcMkb_uK4DAZW3CpvO79-vnEOKxA/edit?usp=sharing) and let me know if you have any questions.

**Comment by YeeCY** [comment]
Thanks for the quick response! It's really helpful. I can add a new RL unit
into the map now. However, the python program is still stuck at "Sending
ResponseJoinGame".
I just want to add some advanced units such as ultralisk and dark templar
into the game. There should be some modifications in the code too. Could
you please give any guidance?

**Comment by samvelyan** [comment]
1. Did you add the map info here `https://github.com/oxwhirl/smac/blob/master/smac/env/starcraft2/maps/smac_maps.py`? Go ahead and add it, should be straightforward.
2. Are the triggers in the .SC2Map file similar to the existing ones (say `3m_3m.SC2Map`)?

**Comment by YeeCY** [comment]
Yes. I just add an ultralisk and  an overseer for the RL player and a dark templar for the enemy based on the 3m.SC2Map. And I add my map file into the SMAC_Maps folder with its configuration like this:
```
...
"1o_1u_vs_1dt": {
        "n_agents": 2,
        "n_enemies": 1,
        "limit": 200,
        "a_race": "Z",
        "b_race": "P",
        "unit_type_bits": 2,
        "map_type": "overseer_ultralisk_and_dark_templar",
    },
...
```
The `get_unit_type_id` function looks like:

```
    def get_unit_type_id(self, unit, ally):
        """Returns the ID of unit type in the given scenario."""
        if ally:  # use new SC2 unit types
            if self.map_type == "overseer_ultralisk_and_dark_templar":
                # ultralisk_rl
                if unit.unit_type == 1971:
                    type_id = 0
                # overseer_rl
                elif unit.unit_type == 1972:
                    type_id = 1
            else:
                type_id = unit.unit_type - self._min_unit_type
        else:  # use default SC2 unit types
            if self.map_type == "stalkers_and_zealots":
                # id(Stalker) = 74, id(Zealot) = 73
                type_id = unit.unit_type - 73
            elif self.map_type == "bane":
                if unit.unit_type == 9:
                    type_id = 0
                else:
                    type_id = 1
            elif self.map_type == "MMM":
                if unit.unit_type == 51:
                    type_id = 0
                elif unit.unit_type == 48:
                    type_id = 1
                else:
                    type_id = 2
            elif self.map_type == "overseer_ultralisk_and_dark_templar":
                # dark templar
                type_id = 0

        return type_id
```
And the max shield for the dark templar:

```
    def unit_max_shield(self, unit):
        """Returns maximal shield for a given unit."""
        if unit.unit_type == 74 or unit.unit_type == self.stalker_id:
            return 80  # Protoss's Stalker
        if unit.unit_type == 73 or unit.unit_type == self.zealot_id:
            return 50  # Protoss's Zaelot
        if unit.unit_type == 4 or unit.unit_type == self.colossus_id:
            return 150  # Protoss's Colossus
        if unit.unit_type == 76 or unit.unit_type == self.dark_templar_id:
            return 80  # Protoss's Dark Templar
```
with
```
self.stalker_id = self.colossus_id = self.zealot_id = self.dark_templar_id = 0
```
Do I miss something?

**Comment by YeeCY** [comment]
By the way, [here](https://drive.google.com/file/d/1IHkJNd2ivLpl2A_TPIqyvMDBRCk0GufB/view?usp=sharing) is my map.

**Comment by samvelyan** [comment]
I'll take a look and get back to you.

**Comment by samvelyan** [comment]
wrt point 3 - this is not a SMAC issue but rather a StarCraft 2.

Anyway, let me know if you have difficulties in the future! :)
