### ISSUE TITLE
Run-time spawn support

### ISSUE THREAD

**Issue by YeeCY** [oxwhirl/smac#14]
With the help of SC2 Editor, we can create units during one episode of the game. It seems smac only supports static spawn currently.  I mean we must specify the number of agents and the number of enemies in the map configuration like this:

```
"3m": {
        "n_agents": 3,
        "n_enemies": 3,
        "limit": 60,
        "a_race": "T",
        "b_race": "T",
        "unit_type_bits": 0,
        "map_type": "marines",
    }
```

And we have to spawn all the units for an episode at the very beginning. 

Is it possible to create some interfaces to handle the dynamic spawn units during the game?

**Comment by samvelyan** [comment]
Yes, it is indeed possible. The [debug API of sc2client-proto](https://github.com/Blizzard/s2client-proto/blob/master/s2clientprotocol/debug.proto) includes the `DebugCreateUnit` command which can be used to create units programmatically. It isn't part of the smac codebase, but I think using it should be straightforward. 

I'm ready to help if there are any problems.

**Comment by YeeCY** [comment]
OK, thanks for your help anyway!
