### ISSUE TITLE
Disable the text messages

### ISSUE THREAD

**Issue by starry-sky6688** [oxwhirl/smac#15]
Hi, I want to disable the text messages(eg "KillUnitBtTag 46") because I need to show the performence of my algorithm by video. Can you tell me how to do this?

**Comment by starry-sky6688** [comment]
![a](https://user-images.githubusercontent.com/38175678/65675114-4041ca80-e080-11e9-983e-4e1f42d0d8f7.png)

**Comment by samvelyan** [comment]
Hi there. I'm not really sure if this is possible. I'm using the [debug commands on sc2-client proto](https://github.com/Blizzard/s2client-proto/blob/master/s2clientprotocol/debug.proto) to kill the units and there seems to be no flag for showing/not showing the commands. Perhaps it can be disabled from the game menu, but I haven't really found from where.

**Comment by lionsq** [comment]
I am curious about how to use the debug commands in SMAC to disable the texts.

**Comment by Duke-Allen** [comment]
> Hi, I want to disable the text messages(eg "KillUnitBtTag 46") because I need to show the performence of my algorithm by video. Can you tell me how to do this?

Hey, Do you know how to disable the text messages(eg "KillUnitBtTag 46")? I also want to disable the text. Thanks a lot.
