### ISSUE TITLE
Not able to run random_agents with PySC2 3.0.0

### ISSUE THREAD

**Issue by PMatthaei** [oxwhirl/smac#16]
Hi,
I can not run the base random_agents example after following exact guidelines with PySC2 3.0.0. With version 2.0.2, however, it works fine. The following error is thrown with 3.0.0.

> Traceback (most recent call last):
>   File "/home/patrick/Projects/sc2-project-thesis/main_smac.py", line 39, in <module>
>     main()
>   File "/home/patrick/Projects/sc2-project-thesis/main_smac.py", line 15, in main
>     env.reset()
>   File "/home/patrick/miniconda3/envs/sc2-project-thesis/lib/python3.7/site-packages/smac/env/starcraft2/starcraft2.py", line 338, in reset
>     self._launch()
>   File "/home/patrick/miniconda3/envs/sc2-project-thesis/lib/python3.7/site-packages/smac/env/starcraft2/starcraft2.py", line 288, in _launch
>     window_size=self.window_size)
>   File "/home/patrick/miniconda3/envs/sc2-project-thesis/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 205, in start
>     want_rgb=want_rgb, extra_args=extra_args, **kwargs)
>   File "/home/patrick/miniconda3/envs/sc2-project-thesis/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 88, in start
>     self, exec_path=exec_path, version=self.version, **kwargs)
> TypeError: type object got multiple values for keyword argument 'version'

**Comment by samvelyan** [comment]
Hi @PMatthaei 

PySC2 3.0.0 was only released yesterday. I'll take a close look at what might have been broken by this release and commit the necessary changes.

**Comment by samvelyan** [comment]
Fixed in https://github.com/oxwhirl/smac/commit/85d496d62fccea285bfc301ebe7757969014a378.

**Comment by PMatthaei** [comment]
Fix works for me. Thank you :) !
