### ISSUE TITLE
ubuntu failed to find EGL functions in library file!

### ISSUE THREAD

**Issue by lml519** [oxwhirl/smac#17]
First, I'd like to thank you for all release,which helps me alot in my research.

However, when i run this command "python -m smac.examples.random_agents", the output display that after Attempting to initialize EGL from file linEGL.so.1 ...  failed to findEGL functions in libary file!

**Comment by lml519** [comment]
![GitHub Logo](E:/出现问题.png)
Format: ![Alt Text](url)

**Comment by samvelyan** [comment]
SMAC itself is not using EGL, but PySC2 does. Perhaps this can help - https://github.com/deepmind/pysc2/issues/207.

**Comment by gjcamacho** [comment]
I know is a little bit late, but I fixed my issue by correctly specifying the path to my libEGL NVIDIA libraries in LD_LIBRARY_PATH, and it worked much more faster than using libOSMesa
