### ISSUE TITLE
Question on difficulties

### ISSUE THREAD

**Issue by cu-rie** [oxwhirl/smac#18]
Even I try the maximum difficulty ("7": sc_pb.VeryHard), and when the number of agents is larger than the number of enemies ("27m_vs_30m"),  the agent wins in every scenario without training (random action). Is there a way to adjust the rule of enemies or custom maps?

**Comment by samvelyan** [comment]
In the 27m_vs_30m scenario, there are 27 units for allies and 30 for the opponent. So the allies are actually outnumbered. 

What is the exact command that you run? I can't see how this could be the case. W/o the training, agents cannot win most of the time, especially on a hard map such as 27m_vs_30m.

You can create your own custom maps and adjust the size of the opponent's army. As stated in the paper and documentation, the difficulty (e.g. sc_pb.VeryHard) doesn't have much effect on the opponent's policy on these maps.
