### ISSUE TITLE
how to close the game render???

### ISSUE THREAD

**Issue by hxx1996** [oxwhirl/smac#20]
I want to close the render,but have not found some functions to control render

**Comment by samvelyan** [comment]
Thanks for the suggestion. I'll look into this.

**Comment by Bingoyww** [comment]
I use MacOS, and  also have  the same issue. So what's the solution to close the GUI?

**Comment by samvelyan** [comment]
It is not possible to close SC2 client UI on MacOs/Windows. See [this thread](https://github.com/deepmind/pysc2/issues/91) for more info.
