### ISSUE TITLE
showing gui

### ISSUE THREAD

**Issue by esquires** [oxwhirl/smac#3]
Thanks for putting together this repo. 

I am trying to figure out how to show a game window to see what is happening. When I run ``python -m smac.examples.random_agents`` or the sample program from the README, nothing seems to show up. Can you help me figure out what might be going wrong?

I am using Starcraft II v 4.7.1 and am on `7678571` in this repo. Here is the output when I run  ``python -m smac.examples.random_agents``. When I run ``python -m pysc2.bin.agent --map Simple64`` from pysc2 a window seems to pop up fine (the ``render interface disabled`` line also shows up there too when I can see a gui).

Also, I noticed that nothing is showing up in ``~/StarCraftII/Replays``. Where does a replay show up? Thanks.

```[bash]
Version: B70326 (SC2.2018Season4)
Build: Nov 27 2018 03:26:30
Command Line: '"/home/esquires3/StarCraftII/Versions/Base70154/SC2_x64" -listen 127.0.0.1 -port 20293 -dataDir /home/esquires3/StarCraftII/ -tempDir /tmp/sc-5lbi516w/ -displayMode 0 -windowwidt
h 1920 -windowheight 1200 -windowx 50 -windowy 50 -eglpath libEGL.so'
Starting up...
Startup Phase 1 complete
Startup Phase 2 complete
Attempting to initialize EGL from file libEGL.so ...
Failed to find EGL functions in library file!
Creating stub renderer...
Listening on: 127.0.0.1:20293
Startup Phase 3 complete. Ready for commands.
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface disabled
Configure: score interface disabled
Configure: render interface disabled
Entering load game phase.
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Game has started.
Sending ResponseJoinGame
Total reward in episode 0 = 0.375
Total reward in episode 1 = 0.75
Total reward in episode 2 = 0.5625
Total reward in episode 3 = 0.9375
Total reward in episode 4 = 0.75
Total reward in episode 5 = 0.1875
Total reward in episode 6 = 0.9375
Total reward in episode 7 = 0.5625
Total reward in episode 8 = 0.5625
Total reward in episode 9 = 0.5625
RequestQuit command received.
Closing Application...
unable to parse websocket frame.
Terminate action already called.
Entering core terminate.
Core shutdown finished.


```

**Comment by TimeBreaker** [comment]
I have exactly the same problem.
But when I try to run pysc2 by "python3 -m pysc2.bin.agent --map Simple64" the game runs normally.

**Comment by eugenevinitsky** [comment]
@esquires Did you install pysc2 as well?

**Comment by samvelyan** [comment]
Hi @esquires,

My sincere apologies for the late reply. Could you please specify which OS are you using? I'm certain that the older versions of pysc2 did not have a graphical component for SC2 on Linux. If there are any changes on their side and SC2 GUI can be turned on, I'll add the features in SMAC as well.

The Replays should indeed appear in $SC2PATH/Replays directory. However, the random_agents script does not generate any replays. Please refer to [pymarl](https://github.com/oxwhirl/pymarl) README for guidelines on how to save SC2Replays.

**Comment by esquires** [comment]
No worries @samvelyan. I appreciate you following up. My confusion is mostly that the pysc2 command seems to produce a gui but the smac command does not. These are the last two commands below.

I am on Ubuntu 16.04 but have also tried it on 18.04. Here are a list of commands I did to get started:

```[bash]
# get starcraft
cd ~
wget http://blzdistsc2-a.akamaihd.net/Linux/SC2.4.7.1.zip
unzip -P iagreetotheeula SC2.4.7.1.zip

urls=(
    https://github.com/oxwhirl/smac/files/2760783/SMAC_Maps.zip
    http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2017Season1.zip
    http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2017Season2.zip
    http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2017Season3_Updated.zip
    http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2017Season4.zip
    http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2018Season1.zip
    http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2018Season2_Updated.zip
    http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2018Season3.zip
    http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2018Season4.zip
    http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2019Season1.zip
    http://blzdistsc2-a.akamaihd.net/MapPacks/Melee.zip
)

for url in ${urls[@]}; do
    wget $url
    fname=$(echo $url | rev | cut -d '/' -f 1 | rev)
    unzip -P iagreetotheeula -d ~/StarCraftII/Maps  $fname 
done

wget https://github.com/deepmind/pysc2/releases/download/v1.2/mini_games.zip
unzip mini_games.zip -d ~/StarCraftII/Maps

# make a virtual environment
mkdir -p ~/venvs
cd ~/venvs
python3.5 -m venv smac2
source ~/venvs/smac2/bin/activate
pip install --upgrade wheel setuptools

# install latest version of pysc2 based on previous comment
mkdir ~/repos/rl -p
cd ~/repos/rl
git clone https://github.com/deepmind/pysc2
pip install -e pysc2

# install smac
cd ~/repos/rl
git clone https://github.com/oxwhirl/smac
pip install -e smac

# test installation
cd ~
python -m smac.bin.map_list # this one looks fine (no gui expected)
python -m smac.examples.random_agents # this one seems like it should have a gui but doesn't
python -m pysc2.bin.agent --map Simple64 # this one produces a gui
```

**Comment by samvelyan** [comment]
Many thanks for all the information @esquires. I'll take a close look at this and get back to you.

**Comment by esquires** [comment]
Hi @samvelyan . I see you added a help wanted label. Did you need any additional information from me?

**Comment by samvelyan** [comment]
Hi @esquires. No actually I've added the label to indicate that this is a 'help wanted'-kind of issue. Sorry for the confusion, I may have added a wrong label here.

**Comment by esquires** [comment]
Is there an object responsible for rendering in smac? I saw in the ``pysc2`` code there is a ``RenderHuman`` object that gets it data from the controller but didn't see a corresponding object in the smac codebase.

**Comment by samvelyan** [comment]
No, we are not doing any rendering in SMAC. 

Sorry, I've haven't been able to find time to look at this yet. Had a very hectic schedule during the past few weeks, and, unfortunately, during the next two weeks as well.

**Comment by wyixiang** [comment]
I have the same problem on Ubuntu 18.04. Is there any solution now?

**Comment by PiggyGenius** [comment]
The only way to watch a replay on SMAC is to play it from the windows game ? There is no way to watch it with deteriorated graphics as in pysc2 ?
What is the meaning of the "watch a replay" section on README then ?

**Comment by Mohan-Zhang-u** [comment]
sorry, same problem on Ubuntu 18.04 as well. "python -m pysc2.bin.agent --map Simple64" works fine with GUI but "python -m smac.examples.random_agents" generates similar error message:

`python -m smac.examples.random_agents
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/home/user1/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 19757 -dataDir /home/user1/StarCraftII/ -tempDir /tmp/sc-pkx0j8ie/ -eglpath libEGL.so'
Starting up...
Startup Phase 1 complete
Startup Phase 2 complete
Attempting to initialize EGL from file libEGL.so ...
Successfully loaded EGL library!
Failed to create and initialize a valid EGL display! Devices tried: 0

CreateInitializedEGLDisplay Failed.
Failed to initialize GL framework
Creating stub renderer...
Listening on: 127.0.0.1:19757
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:57120 accepted
ReadyHandler: 127.0.0.1:57120 ready
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface disabled
Configure: score interface disabled
Configure: render interface disabled
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Game has started.
Successfully loaded stable ids: /home/user1/StarCraftII/stableid.json
Sending ResponseJoinGame
Total reward in episode 0 = 2.0625
Total reward in episode 1 = 0.9375
Total reward in episode 2 = 1.5
Total reward in episode 3 = 2.25
Total reward in episode 4 = 1.125
Total reward in episode 5 = 1.875
Total reward in episode 6 = 2.4375
Total reward in episode 7 = 1.5
Total reward in episode 8 = 2.25
Total reward in episode 9 = 1.875
RequestQuit command received.
Closing Application...
DataHandler: unable to parse websocket frame.
CloseHandler: 127.0.0.1:57120 disconnected
ResponseThread: No connection, dropping the response.
`

**Comment by samvelyan** [comment]
Hi @esquires ,

I'm terribly sorry for getting back to you so late regarding this (OMG, it's been more than a year).

I've tried to replicate your results and followed your aforementioned steps on Ubuntu 16.04. Unfortunately, running the last command was unsuccessful for me. I specifically got [this error](https://github.com/deepmind/pysc2/issues/282), which doesn't seem to be solved yet.

Anyway, do you recall which GUI did you see? Is it StarCraft II window (bottom left) or StarCraft Viewer (top right)? 

<img width="1098" alt="Screenshot 2020-08-04 at 16 42 09" src="https://user-images.githubusercontent.com/9724413/89295154-9e144b00-d671-11ea-85bd-5f469c043c82.png">

The screen is from my MacOS laptop.

**Comment by 4ever-Rain** [comment]
I have the same problem on Ubuntu 20.04, when I run` python -m smac.examples.random_agents`
However, when I run `python -m pysc2.bin.agent --map Simple64` , I can see StarCraft Viewer (top right).
@samvelyan I think pysc2 can work well by `pip install pysc2 (v3.0.0)` with the  Starcraft II v 4.10

**Comment by samvelyan** [comment]
We now have pygame environment rendering, which can be used via the `render()` method (see example in the Readme). Please reopen if there are any issues.
