### ISSUE TITLE
Why are unit type IDs handled differently between allied and enemy units?

### ISSUE THREAD

**Issue by douglasrizzo** [oxwhirl/smac#33]
I have a question concerning the `get_unit_type_id()` method. I noticed that there is a different procedure to generate unit types for allied and enemy units. This results in units of the same type (inside SC2) to have different type IDs returned by `get_unit_type_id()` depending if they are allies or enemies. However, this only happens in some maps, while other maps keep consistent enemy type IDs for allies and enemies (I believe that by coincidence and not on purpose). For example:

* in maps `2s3z` and `3s5z_vs_3s6z`, allied stalkers are represented (in one-hot encoding) as 10 and zealots as 01, while enemy stalkers are represented as 01 and zealots as 10.
* In `MMM2`, Marauders, Marines and Medivacs are labeled as 001, 010 and 100 for both allied and enemy units.

Is there a reason why allied and enemy unit type IDs are treated differently? Would there be any side effects if they were to be handled in the same way?

**Comment by douglasrizzo** [comment]
I think I have found the answer to my question. In all scenarios, the number of unit types in the allied and enemy teams are the same, so SMAC uses the same number of 'bits' to encode unit types for both teams. This doesn't mean that the unit types themselves are the same, as in `2m_vs_1z`, where each team has the same number of unit types (1), so SMAC doesn't even provide unit type IDs to tell them apart.

I hope you accept a pull request in which I expose unit type IDs, by providing a list with their default unit types, as provided by SC2.

**Comment by douglasrizzo** [comment]
I did some debugging and found out that the SC2 client API returns allied and enemy units with different IDs. For example, in 2s3z, an allied Stalker has ID 1970 and a Zealot has ID 1971, while the enemy units have IDs 74 and 73.

That's a bummer. Is there a way I can get the [usual unit types](https://github.com/Blizzard/s2client-api/blob/d9ba0a33d6ce9d233c2a4ee988360c188fbe9dbf/include/sc2api/sc2_typeenums.h#L25) in the SMAC maps?

**Comment by samvelyan** [comment]
Yes. The reason for this is that we don’t use regular SC2 units but rather slightly changed versions of them (which I name x_RL in the SC2 Editor) for allies. Basically, the default SC2 units have certain features which we wanted to disable for our RL agents. For instance, when a SC2 unit is under attack, it automatically starts attacking the units that is shooting at it. We wanted the RL agents to start shooting once they understand that it is necessary. What we’ve basically done is we copied the SC2 units in the Editor, changed 3 fields in their characteristics, and named it Unitname_RL (there is a paragraph about this at the Appendix of the SMAC paper). All of the SMAC maps feature such units for the ally team.
