### ISSUE TITLE
How to set visualize the game？

### ISSUE THREAD

**Issue by xxd819240366** [oxwhirl/smac#37]
When I used "python3 src/main.py --config=qmix --env-config=sc2 with env_args.map_name=2s3z",I want to  visualize the game to see how agents work.
But i don't find any parameters can do this.

**Comment by samvelyan** [comment]
This can only be done if you're using Mac or Windows versions of SC2. In those systems, the GUI will automatically appear on your screen. If you're using Linux, consider using Wine.

Hope this helps.

**Comment by xxd819240366** [comment]
Unfortunately，I'm using Ubuntu18.04.My lab computer use win10,maybe i should wait util i can go to school.......

**Comment by samvelyan** [comment]
There already are [issues for the same thing ](https://github.com/oxwhirl/smac/issues/3), so I'm closing this one.

**Comment by xxd819240366** [comment]
Ok
