### ISSUE TITLE
Is it possible to configure any number of agents?

### ISSUE THREAD

**Issue by stweiyy** [oxwhirl/smac#38]
Is it possible to configure any number of agents or enemies?

Refer to https://github.com/oxwhirl/smac/issues/14

In smac_maps.py 
"3m": {
        "n_agents": 3,
        "n_enemies": 3,
        "limit": 60,
        "a_race": "T",
        "b_race": "T",
        "unit_type_bits": 0,
        "map_type": "marines",
    }

say if I want 5 agents, then I change n_agents to 5, 
However, it seems directly change this the RL algorithm will throw and Exception.

so is the number of agents or enemies are binded to the specific map file. so the smac_maps.py file just repeat the dict entry for other number of agents like 8m, 25m??

**Comment by samvelyan** [comment]
Yes, the number of agents and enemies are both fixed for the specific map file which we created using the StarCraft II Editor. If you would like to try on a custom map/scenario that isn't present in our list, you are going to need to create it using the Editor and add the appropriate information in SMAC.

**Comment by stweiyy** [comment]
I see. many thanks!
