### ISSUE TITLE
Description of the level of built-in AI

### ISSUE THREAD

**Issue by tania2333** [oxwhirl/smac#39]
As is described in the documentation, the built-in AI is set to level 7 -"very difficult". I guess AI of level 7 is more intelligent than lower level but I don't quite know the concrete settings of this level. Maybe the enemies of level-7 can share their observations while the enemies of lower levels can't, I guess. Could someone give the description of the specific settings of every level?

**Comment by samvelyan** [comment]
[Here](https://liquipedia.net/starcraft2/Artificial_Intelligence) is some information about AI levels on StarCtaft II Liquipedia.

For our experiments using the micro scenarios in SMAC, we noticed no difference between levels 7 and 10. We assume that these difficulties play a more major role for macro, but have little to no effect on rather small unit micromanagement.

**Comment by tania2333** [comment]
Thank you for the reply.
