### ISSUE TITLE
A question about effective shooting

### ISSUE THREAD

**Issue by tania2333** [oxwhirl/smac#40]
Hello. In fact, I try to train the agents under the scenario 2m_vs_1z but I found that even the zealot is in the shooting range of our agents and it's attacked, its health keeps the same as before.  I think the health of zealot should reduce but it doesn't. So I wonder why the attack isn't effective as I imagined. I guess maybe there is an effective attack ratio or the zealot can dodge. Could you please explain this? Thanks in advance.

**Comment by samvelyan** [comment]
Zealot, as other Protus units, has a shield which takes damage first. Once all the shield points are gone, only then an enemy's damage results in unit's health loss. 

Did you check the shield of the zealot?

**Comment by tania2333** [comment]
The sum of shield and original health is regarded as a new total health and this new total health doesn't reduce when zealot is attacked. I'm sorry that I forget to say this.

**Comment by samvelyan** [comment]
I've just tried it and it works fine for me. Can you run the `smac/examples/random_agents.py` script but replace line 10 with the following?
```python
env = StarCraft2Env(map_name="2m_vs_1z", heuristic_ai=True, heuristic_rest=True)
```

**Comment by tania2333** [comment]
I tried this script and it has the same problem. If you debug and observe the health of zealot attacked during one episode and you will find that when zealot is attacked, the health of zealot reduced for most of the time but sometimes it didn't reduce. I mean sometimes the health of zealot didn't reduce as imagined but other times it's correct.

**Comment by samvelyan** [comment]
Oh, I see. It must be purely game-related then. I suggest you try to find the answer in StarCraft II forums, for example. In SMAC, we simply call the `attack` command of the game when the agent choses so and in no way interfere it.

**Comment by tania2333** [comment]
OK, I understand. Thanks a lot!
