### ISSUE TITLE
How to judge win or lose

### ISSUE THREAD

**Issue by starry-sky6688** [oxwhirl/smac#41]
Hi, I'm wondering how to judge win or lose. 

 I judged it by comparing the cumulative rewards with 19.9，it says,  if  cumulative rewards > 19.9, I think it wins，is it right? 

Because I find the cumulative rewards is sometimes like 19.9999999, so I don't use 20. 

Looking forward to your reply.

**Comment by samvelyan** [comment]
Hi there!

The `step()` function in StarCraft2Env returns all the necessary information after each timestep. You can check if the episode has terminated (second return value of `step()` function) and the `info` dictionary includes `battle_won=True` (third return value of `step()` function). 

Hope this helps.
