### ISSUE TITLE
Qmix code seems cannot learn good policy

### ISSUE THREAD

**Issue by GoingMyWay** [oxwhirl/smac#42]
I run the example code of qmix and it seems that it cannot learn good policy. The reward is nearly random policy.

**Comment by samvelyan** [comment]
What QMIX code are you running?

**Comment by GoingMyWay** [comment]
> What QMIX code are you running?

Thanks for fast response, I use the code: https://github.com/oxwhirl/smac/blob/master/smac/examples/rllib/run_qmix.py

**Comment by samvelyan** [comment]
Have you tried using [oxwhirl/pymarl](https://github.com/oxwhirl/pymarl)? That's the codebase the results of our paper are based on. The RLlib examples here are provided by our friends from Berkeley who integrated QMIX with their RLlib library. Therefore, there are likely to be differences in results.

**Comment by GoingMyWay** [comment]
> Have you tried using [oxwhirl/pymarl](https://github.com/oxwhirl/pymarl)? That's the codebase the results of our paper are based on. The RLlib examples here are provided by our friends from Berkeley who integrated QMIX with their RLlib library. Therefore, there are likely to be differences in results.

Wow, looks good, I did not try it. I will try it. Is the QMIX from RLlib wrong?

**Comment by samvelyan** [comment]
There are some notable differences. For example, the RLlib qmix code doesn't use the global state that smac provides and instead uses only per-agent observations.

**Comment by GoingMyWay** [comment]
> There are some notable differences. For example, the RLlib qmix code doesn't use the global state that smac provides and instead uses only per-agent observations.

Thanks, that's a big difference. So, I think that is the reason why QMIX from Rllib fails to learn a good policy.

**Comment by samvelyan** [comment]
No problem. Let us know should you face any issues.
