### ISSUE TITLE
Will you add mini-games ?

### ISSUE THREAD

**Issue by GoingMyWay** [oxwhirl/smac#43]
mini-games from pysc2 are also good and challenging, will you add them into SMAC in the future?

**Comment by samvelyan** [comment]
We have no plans on adding mini-games to SMAC. Should you wish to try or/and them to SMAC, I'm more than happy to help.

**Comment by GoingMyWay** [comment]
> We have no plans on adding mini-games to SMAC. Should you wish to try or/and them to SMAC, I'm more than happy to help.

Hi, I want to add mini-games to SMAC these days, how can I get started?

**Comment by samvelyan** [comment]
I've added some information on this in README. Please take a look [here](https://github.com/oxwhirl/smac/blob/master/README.md#creating-new-maps) as a start. Should you have any questions, please feel free to reopen the issue or reach me by email. Cheers.

**Comment by GoingMyWay** [comment]
> I've added some information on this in README. Please take a look [here](https://github.com/oxwhirl/smac/blob/master/README.md#creating-new-maps) as a start. Should you have any questions, please feel free to reopen the issue or reach me by email. Cheers.

Great, thanks, I will try it.
