### ISSUE TITLE
ValueError: Map 'SMAC_Maps/2s3z.SC2Map' not found.

### ISSUE THREAD

**Issue by AchrafMoussaid** [oxwhirl/smac#44]
Hi everyone, I'm trying to run an experiment using python3 src/main.py --config=qmix --env-config=sc2 with env_args.map_name=2s3z from the project https://github.com/oxwhirl/pymarl, and I got this Error, 
<img width="938" alt="gi" src="https://user-images.githubusercontent.com/31735009/84570541-16ebda80-ad86-11ea-91c5-493aaec0a573.PNG">
<img width="836" alt="git" src="https://user-images.githubusercontent.com/31735009/84570545-18b59e00-ad86-11ea-85dc-a1930cdd07c4.PNG">

ValueError: Map 'SMAC_Maps/2s3z.SC2Map' not found.
The error message in detail is presented in the picture
Can I get help please !
Thank you

**Comment by samvelyan** [comment]
Hi! The `SMAC_Maps` directory needs to be copied to `$SC2PATH/Maps` directory, as described [here](https://github.com/oxwhirl/smac#smac-maps). In your case, I see your `$SC2PATH` is at `~/pymarl/src/3rdparty/StarCraftII`. So just copy the `SMAC_Maps directory` to `~/pymarl/src/3rdparty/StarCraftII/Maps`.

**Comment by samvelyan** [comment]
I think the issue will be solved for you if you follow the steps above. If not, feel free to reopen the issue.
