### ISSUE TITLE
How to save/reload the game env's seed?

### ISSUE THREAD

**Issue by yuchen-x** [oxwhirl/smac#45]
To Whom It May Concern,

I am working on implementing saving ckpt for my experiments, but I got a problem with getting the random state of the game env and re-setting it when I resume my experiments. 

I noticed that the game env is created in the following way:

`create = sc_pb.RequestCreateGame(local_map=sc_pb.LocalMap(), realtime=False, random_seed=self._seed)`

where the seed is passed in. 

I was wondering:

1) how to get the random state of the created game when saving the ckpt?
2) how to set the random state for the game env using saved random state type value rather than a seed number?

Thank you very much!

**Comment by samvelyan** [comment]
Hi @yuchen-x . Unfortunately, this functionality is not implemented in PySC2 (the library that SMAC uses to communicate with StarCraft II).
