### ISSUE TITLE
Scenarios 3s_vs_3z and 3s_vs_4z Difficulty Category

### ISSUE THREAD

**Issue by xiaoyuch24** [oxwhirl/smac#52]
Hi all,

Is there a place where I can find the difficulty category for all scenarios? 

I noticed 3s_vs_5z was counted as a hard scenario in SMAC paper. How about 3s_vs_3z or 3s_vs_4z? 

Thanks!

**Comment by samvelyan** [comment]
Hi @xiaoyuch24 ,

In the first version of our paper (available on arxiv), we included results from 3s_vs_3z and 3s_vs_4z. They were both included as a part of *easy* scenarios.
