### ISSUE TITLE
Redis cannot be initialized when running the qmix sample

### ISSUE THREAD

**Issue by sihuaiwei** [oxwhirl/smac#61]
File "G:\anaconda3\envs\SMAC\lib\site-packages\ray\services.py", line 582, in wait_for_redis_to_start
    raise RuntimeError("Unable to connect to Redis. If the Redis instance "
RuntimeError: Unable to connect to Redis. If the Redis instance is on a different machine, check that your firewall is configured properly.

Process finished with exit code 1

**Comment by GoingMyWay** [comment]
I think it's not an issue of SMAC. It is an issue of Ray. Because you are using Ray to run QMIX. You can open an issue in Ray's repo.
