### ISSUE TITLE
How can I get the reward of each agent at each step.

### ISSUE THREAD

**Issue by GoingMyWay** [oxwhirl/smac#64]
Dear @douglasrizzo, do you know how to get the reward of each agent at each step? Now, SMAC only returns a global reward. How can I change the setting to make SMAC return each agent's individual reward?

**Comment by samvelyan** [comment]
SMAC doesn't provide individual per-agent rewards since it is meant to be a testbed for cooperative MARL where the reward is shared between all agents. If you want, you can modify `starcraft2.py` and shape per-agent reward. However, this would completely change the problem setting.

**Comment by GoingMyWay** [comment]
> SMAC doesn't provide individual per-agent rewards since it is meant to be a testbed for cooperative MARL where the reward is shared between all agents. If you want, you can modify `starcraft2.py` and shape per-agent reward. However, this would completely change the problem setting.

Thank you. Yes, I agree it will change the problem setting. I am exploring new problems with SMAC.
