### ISSUE TITLE
Question on the index of ally_feats

### ISSUE THREAD

**Issue by GoingMyWay** [oxwhirl/smac#65]
In https://github.com/oxwhirl/smac/blob/master/smac/env/starcraft2/starcraft2.py#L957, 

I found the `ally_feats` uses the index of `i` not `al_id` to set values, is it right? Since the `i` is from `enumerate(al_ids)`. I think `al_id` should be used rather than `i`.

@douglasrizzo @samvelyan Could you please check it?

**Comment by douglasrizzo** [comment]
Sorry for the shameful delay. That code was there from before the time I started using SMAC. It looks OK, though. It uses `al_id` to get info on the allies and `i` to iterate through the rows of a numpy array (not coincidentally, there is one row in the array for each ally) and put the info from the current agent in that row.
