### ISSUE TITLE
SC2 screen message during training

### ISSUE THREAD

**Issue by Massar88** [oxwhirl/smac#67]
Hi, 
Can you please let me know how to get rid of or delete the message (CHEAT local player KillUnitTagBy..) that appears on the game screen during the training?
With many thanks
![SC2 message](https://user-images.githubusercontent.com/79666658/109338919-23d13100-7824-11eb-9380-a714e00abcd6.JPG)

**Comment by samvelyan** [comment]
This massage is being printed by the sc2proto-api that we use to communicate with the game. This isn't done by SMAC. I don't think we can do anything about it.
