### ISSUE TITLE
How to add the pysc2 built-in map to this framework?

### ISSUE THREAD

**Issue by hijkzzz** [oxwhirl/smac#68]
Hi~

I found SMAC maps are not very difficult to solve, is it possible to add pysc2 maps to this framework?

**Comment by samvelyan** [comment]
[Here](https://github.com/oxwhirl/smac#creating-new-maps) are the instructions on how to create maps for SMAC. Whether a pysc2 or other map, they will need to be modified to be similar to ours in terms of RL units and triggers in SC2 Editor.
