### ISSUE TITLE
More maps?

### ISSUE THREAD

**Issue by saizhang0218** [oxwhirl/smac#7]
Hi, I want to evaluate on the 1c_3s_5z map, which is used as a benchmark for the QMIX paper, I can not find it under this directory: smac/smac/env/starcraft2/maps/SMAC_Maps/
Can you upload this map? Or is there any equivalent maps I can use? Thanks!

**Comment by samvelyan** [comment]
Hi @saizhang0218. Unfortunately, the older maps from the QMIX paper are incompatible with the current codebase (smac & pymarl). 

Nonetheless, you can always create your own maps using the StarCraft 2 Editor by modifying the released .SC2Map files. I'd suggest taking a look at one of them (e.g., 3s_5z) and then adding the Colossus unit to it. This would require you to create a new "Colossus RL" unit (check out the second to last paragraph from [here](https://github.com/oxwhirl/smac/blob/master/docs/smac.md#environment-settings) for difference between "RL" and regular units). You would also need to make few changes in the starcraft.py file.

Let me know if you are willing to do this. I'm happy to help if you have any questions.
