### ISSUE TITLE
About the results

### ISSUE THREAD

**Issue by Amanda-1997** [oxwhirl/smac#74]
hi, 

About the x axis, how many steps(or the max-length-limit) did one epoch contain?

**Comment by douglasrizzo** [comment]
Hi @Amanda-1997, if you take at look inside https://github.com/oxwhirl/smac/blob/master/smac/env/starcraft2/maps/smac_maps.py, you'll see that each map has a different `limit` attribute, which is the number of steps before the environment resets to the initial state, in case the episode does not end before that.
