### ISSUE TITLE
How to change the inital position of RL agents and enemies?

### ISSUE THREAD

**Issue by Duke-Allen** [oxwhirl/smac#86]
Hey, I note that the inital position for RL agents is in the same place. Is it possible to change the RL agents inital position, namely the RL agents inital positions are different? Is the enemies inital position changed?
Hope for your reply, thanks.

**Comment by Duke-Allen** [comment]
The SC2 Editor might be used to spawn the RL agents and enemies for different position as follow:
![QQ截图20211117103952](https://user-images.githubusercontent.com/45333787/142112285-531a361c-f51e-4a5e-b888-2ceac13d2915.jpg)

I add another point **"Team1_1"** for RL agents in **3m** map. The Team1 generate two marines, and the Team1_1 spawn one. I test this map by COMA algorithm, it looks well. Is it right? @samvelyan

**Comment by ReinholdM** [comment]
Hi! I have the same request for changing the position with the map editor. But the 3m map only owns two teams and how can I find the marines and edit them? Any suggestions?

**Comment by samvelyan** [comment]
Hi. @Duke-Allen yes, you are correct regarding the spawning locations. I haven't played with the fog options a lot, so cannot comment on that unfortunately.

@ReinholdM, you can add different points and change the unit spawn locations in the `Triggers` menu, as @Duke-Allen described. If you open any SMAC map, you'll see that we're spawning units on a fixed Point. Usually everyone is being spawned on the same group Point. However, you can change the triggers and spawn individual units at different locations (you just have to create those points on the map in advance). 

Hope this is helpful! Feel free to reopen if there are further questions

**Comment by ReinholdM** [comment]
@samvelyan Thanks for your reply. If I want to create a new map with another unit like stalkers near to the marines in 3m map, how can I modify the map file?

**Comment by Duke-Allen** [comment]
> @samvelyan Thanks for your reply. If I want to create a new map with another unit like stalkers near to the marines in 3m map, how can I modify the map file?

You can add another `Point` in 3m map by SC2 Editor.
![QQ截图20211130221434](https://user-images.githubusercontent.com/45333787/144063411-7fcc8d6f-8a8b-4a63-a0d3-474418070960.jpg)
Then add the action for your new point  in `Spawn Marines` by Triggers menu
![QQ截图20211130221859](https://user-images.githubusercontent.com/45333787/144064354-340460fe-a733-4298-a854-e7083773077c.jpg)

Hope it helpful for you.

**Comment by ReinholdM** [comment]
Great thanks for your reply! I will check it
