### ISSUE TITLE
What is the meaning of the "unit_type_bits" in map parameters?

### ISSUE THREAD

**Issue by Duke-Allen** [oxwhirl/smac#87]
<img width="331" alt="微信截图_20211119102444" src="https://user-images.githubusercontent.com/45333787/142554432-c3666b8e-8e8c-42f1-aa48-f14a767e031d.png">

Hey, Does anyone know about the meaning of **unit_type_bits** in `smac_maps.py`? Thanks a lot.

**Comment by Duke-Allen** [comment]
Well, I know

**Comment by funny0619** [comment]
> Well, I know

Since this the worst way anyone can close an issue. This is the [link](https://github.com/oxwhirl/smac/issues/118#issuecomment-1704815140) for a better answer
